spring.application.name=flowcolombia

# Base de datos Neon (PostgreSQL) - Usando variables de entorno
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-soft-tooth-atwmo4vz.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USERNAME:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_UFevk8yVZ1xE}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Admin password
admin.password=FlowColombia2026*

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Límite de subida de archivos
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=2MB

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1