spring.application.name=vibecolombia

# Base de datos Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.eepevqturhgjiinirrnq
spring.datasource.password=VibeColombia2026*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Admin password
admin.password=2026Vibecolombia*

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Límite de subida de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

# Reducir uso de memoria
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
server.tomcat.max-connections=50
server.tomcat.threads.max=10