spring.application.name=vibecolombia

# Base de datos Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.eepevqturhgjiinirrnq
spring.datasource.password=VibeColombia2026*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Admin password
admin.password=2026Vibecolombia*

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false